name: Generate Wiki On Tag

on:
  push:
    tags:
      - '*'

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run output generator
        run: python output_generator.py

      - name: Clone Wiki
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki

      - name: Update Wiki Pages
        run: |
          cd wiki

          rm -f *.md

          cd ..

          cp wiki_outputs/*.md wiki/

          cd wiki
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .
          git commit -m "Update outputs for tag ${{ github.ref_name }}" || echo "No changes"
          git push
